version: '3'
services:
  db:
    image: postgres:12
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=notification_centre
      - POSTGRES_PASSWORD=spanish_inquisition
    ports:
      - 5432:5432